window.AppStep = {
  WELCOME: 'WELCOME',
  MORNING_RECALL: 'MORNING_RECALL',
  MID_MORNING_RECALL: 'MID_MORNING_RECALL',
  MEMORY_ENCODING: 'MEMORY_ENCODING',
  AFTERNOON_RECALL: 'AFTERNOON_RECALL',
  MID_AFTERNOON_RECALL: 'MID_AFTERNOON_RECALL',
  SPATIAL_RECALL: 'SPATIAL_RECALL',
  ANECDOTE: 'ANECDOTE',
  MEMORY_RETRIEVAL: 'MEMORY_RETRIEVAL',
  ANALYSIS: 'ANALYSIS',
  COMPLETED: 'COMPLETED',
  HISTORY: 'HISTORY'
};